#%RAML 1.0
title: fdsafds
protocols: [ HTTP, HTTPS ]
version: 1.0.0
mediaType: application/json

/ping:
  get:
    description: Get Health Check Response Status
    responses:
      200:
        body:
          application/json:

/accounts:
  get:
    description: Get All Users Account Info
    responses:
      200:
        description: Get All Users Account Info Successfully
        body:
          application/json:
  /{user_id}:
    get:
      description: Get An User Account Info

/login:
  post:
    responses:
      200:
        body:
          application/json:
  /attemps:
    get:
      responses:
        200:
          body:
            application/json:

