#%RAML 1.0 DataType
displayName: Health Check Response
type: object

properties:
  status:
    type: string
    enum: [SUCCESS, ERROR, WARNING, FAILED, WAITING]
  timeStamp:
    type: datetime
  transaction:
    type: string
  info:
    type: object
    properties:
      apiName:
        type: string
      version:
        type: string